name: Build JavaFX App

on:
  push:
    branches: [ "master-beta" ]
  pull_request:
    branches: [ "master-beta" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Install JavaFX SDK first
    - name: Install JavaFX
      run: |
        wget https://download2.gluonhq.com/openjfx/21/openjfx-21_linux-x64_bin-sdk.zip
        unzip openjfx-21_linux-x64_bin-sdk.zip
        echo "JAVAFX_HOME=$(pwd)/javafx-sdk-21" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup virtual display
      run: |
        sudo apt-get install -y xvfb libgtk-3-0 libxtst6 libxrender1
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99

    - name: Build with Maven
      run: mvn clean package

    # 2. Fixed JAR test command
    - name: Test JAR execution
      run: |
        java \
          --module-path $JAVAFX_HOME/lib \
          --add-modules javafx.controls,javafx.fxml \
          -jar target/address-book-1.0-SNAPSHOT.jar --headless
