name: JavaFX CI/CD Pipeline

on:
  push:
    branches: [ "master-beta" ]
  pull_request:
    branches: [ "master-beta" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install JavaFX SDK and Linux dependencies
      - name: Setup JavaFX environment
        run: |
          sudo apt-get install -y xvfb libgtk-3-0 libxtst6 libxrender1
          wget https://download2.gluonhq.com/openjfx/21/openjfx-21_linux-x64_bin-sdk.zip
          unzip openjfx-21_linux-x64_bin-sdk.zip
          echo "JAVAFX_HOME=$(pwd)/javafx-sdk-21" >> $GITHUB_ENV
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99

      # 3. Set up JDK 17 with Maven caching
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 4. Build with Java 17 compatibility
      - name: Build with Maven
        run: |
          mvn -B clean package -Dmaven.compiler.source=17 -Dmaven.compiler.target=21

      # 5. Test the JAR with JavaFX modules
      - name: Test JAR execution
        run: |
          java \
            --module-path $JAVAFX_HOME/lib \
            --add-modules javafx.controls,javafx.fxml \
            -jar target/address-book-1.0-SNAPSHOT.jar --headless

      # 6. Dependency graph (kept from original)
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6