name: Run Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Install xvfb for headless tests
        run: sudo apt-get install -y xvfb
        
      - name: Set up virtual display
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x24 > /dev/null 2>&1 &
          
      - name: Run Unit Tests with Maven
        run: xvfb-run --server-args="-screen 0 1920x1080x24" mvn -B test --no-transfer-progress
        env:
          DISPLAY: :99.0
          headless: true